### ISSUE TITLE
`pygit2` backend didn't raise a proper exception in `resolve_rev`.

### ISSUE THREAD

**Issue by karajan1001** [iterative/scmrepo#30] opened 2022-01-28 08:20 UTC
How to reproduce it:
```bash
$ mkdir scmtest
$ cd scmtest
# this is correct
$ python3 -c "from scmrepo.git import Git; Git('.').pygit2.resolve_rev('HEAD~')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 271, in resolve_rev
    raise RevError(f"unknown Git revision '{rev}'")
scmrepo.exceptions.RevError: unknown Git revision 'HEAD~'

# add some remote
$ git remote add origin someremote
# do not wrap the exception properly from `pygit2`
$ python3 -c "from scmrepo.git import Git; Git('.').pygit2.resolve_rev('HEAD~')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 263, in resolve_rev
    shas = {
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 264, in <setcomp>
    self.get_ref(f"refs/remotes/{remote.name}/{rev}")
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 322, in get_ref
    ref = self.repo.references.get(name)
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/pygit2/repository.py", line 1440, in get
    return self[key]
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/pygit2/repository.py", line 1436, in __getitem__
    return self._repository.lookup_reference(name)
_pygit2.InvalidSpecError: refs/remotes/origin/HEAD~: the given reference name 'refs/remotes/origin/HEAD~' is not valid

# gitpython works correctly
python3 -c "from scmrepo.git import Git; Git('.').gitpython.resolve_rev('HEAD~')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/scmrepo/git/backend/gitpython.py", line 352, in resolve_rev
    raise RevError(f"unknown Git revision '{rev}'")
scmrepo.exceptions.RevError: unknown Git revision 'HEAD~'

```

For now, the default backend for `resolve_rev` is `pygit2`, and it causes some problems in https://github.com/iterative/dvc/pull/7204#issuecomment-1021431886. To solve this, we have two choices: 
1. wrap the `_pygit2.InvalidSpecError` from in `pygit2` backend. 
2. use `gitpython` backend instead.

**Comment by pmrowla** [comment] 2022-01-28 08:58
The issue is that this should be resolved in the `resolve_refish` call here:
https://github.com/iterative/scmrepo/blob/2abcdaba87979a4805027f5b3dc9a0ac792fbda3/scmrepo/git/backend/pygit2.py#L253-L271
pygit/libgit should be able to resolve the `~<n>` syntax so this will need some investigation

The fallback `get_ref` call will always fail here since the `~<n>` is always going to be an invalid ref, so changing it to wrap `get_ref` to catch the exception and re-raising `RevError` should also be done, but the main issue here is that `resolve_refish("HEAD~<n>")` is failing for some reason

**Closed** 2022-02-16 07:44 UTC
